### ISSUE TITLE
📦 refactor: change the code folder, structure for new renovation

### ISSUE THREAD

**Issue by nyomansunima** [nyomansunima/personal-site#59]
# About
After a little research on using complex UI in my portfolio website, I realize that sometimes I need to blazingly fast website with small chunks. So that's why i decide to make the website become simple and easy to maintain.

## Tasks

- [x] Create a new schema 
- [x] Create new Web project 
- [x] Connect using special feature
- [x] Testing
- [x] Linting
- [x] Setup project
